// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs5Pnhw7poAACzYh5AqpQphH-NIyoZXq4',
    appId: '1:1041416886097:web:66a396faee00897d1d2570',
    messagingSenderId: '1041416886097',
    projectId: 'lumoapp-c75c6',
    authDomain: 'lumoapp-c75c6.firebaseapp.com',
    storageBucket: 'lumoapp-c75c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVKdG_zM9P-vQQA2TNfeehafyMgVlJvEk',
    appId: '1:1041416886097:android:bb6e258953c525151d2570',
    messagingSenderId: '1041416886097',
    projectId: 'lumoapp-c75c6',
    storageBucket: 'lumoapp-c75c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC73iSe0gHDv4sDevEv3gDo-JKULb-Zm4E',
    appId: '1:1041416886097:ios:3baa499dc1c1e3411d2570',
    messagingSenderId: '1041416886097',
    projectId: 'lumoapp-c75c6',
    storageBucket: 'lumoapp-c75c6.appspot.com',
    iosClientId:
        '1041416886097-s5rt99hfn15aco27vpvmcks670ubflrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC73iSe0gHDv4sDevEv3gDo-JKULb-Zm4E',
    appId: '1:1041416886097:ios:3baa499dc1c1e3411d2570',
    messagingSenderId: '1041416886097',
    projectId: 'lumoapp-c75c6',
    storageBucket: 'lumoapp-c75c6.appspot.com',
    iosClientId:
        '1041416886097-s5rt99hfn15aco27vpvmcks670ubflrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumoApp',
  );
}
